name: Bug Report
description: File a bug report for Xee.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Bug Summary
      description: At a high level, described what happened.
      placeholder: Describe what happened...
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        - Give details that can allow others to reproduce the bug.
        - Make a copy of this [Colab template](https://colab.research.google.com/drive/1vAgfAPhKGJd4G9ZUOzciqZ7MbqJjlMLR)
        - Be sure that any Earth Engine assets used by the script are publicly accessible.
      placeholder: Describe steps in detail...
      value: "1. Item "
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
    id: version
    attributes:
      label: Xee Version
      description: What version of Xee are you running?
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: (OPTIONAL) How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
